micronaut:
  application:
    name: gamsIntegration
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

swagger-ui:
  enabled: true
  theme: flattop

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa.default.properties.hibernate.hbm2ddl.auto: update


gams:
  workspace:
    # gams installation with license
    system-dir: "/opt/gams/gams33.2_linux_x64_64_sfx"
    # any working directory you choose
    working-dir: "gams-working-dir"
  model-file: "gams-working-dir/gams-test-model.gms"