name: github actions gams 

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d ' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

      - name: Git LFS Pull
        run: git lfs pull  

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set docker tag
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
              echo "TAG=${{ secrets.DOCKER_HUB_USERNAME }}/gams:latest,${{ secrets.DOCKER_HUB_USERNAME }}/gams:$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
          else
              echo "TAG=${{ secrets.DOCKER_HUB_USERNAME }}/gams:test-deploy" >> "$GITHUB_ENV"
          fi

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.TAG }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
